# Provisions Firebase for the Angular frontend under frontend/:
#   - enables Firebase on the GCP project and registers a Web App
#   - writes frontend/src/environments/environment.ts from the app's real SDK
#     config, so the manual "copy config from console" step disappears
#   - deploys frontend/firestore.rules (public read / no write on `articles`)
#   - creates a Firebase Hosting site and deploys frontend/dist to it
#
# google_firebase_hosting_version does not support uploading static file
# content (only rewrites/headers config) — actual deploys go through the
# Firebase CLI, wired in via a local-exec provisioner below.

locals {
  hosting_site_id = coalesce(var.hosting_site_id, "${var.project_id}-frontend")
}

resource "google_firebase_project" "default" {
  provider = google-beta
  project  = var.project_id

  depends_on = [google_project_service.apis]
}

resource "google_firebase_web_app" "frontend" {
  provider     = google-beta
  project      = var.project_id
  display_name = "market-rss-sentiment-frontend"

  depends_on = [google_firebase_project.default]
}

data "google_firebase_web_app_config" "frontend" {
  provider   = google-beta
  project    = var.project_id
  web_app_id = google_firebase_web_app.frontend.app_id
}

resource "local_file" "frontend_environment" {
  filename        = "${var.source_dir}/frontend/src/environments/environment.ts"
  file_permission = "0644"
  content         = <<-EOT
    // Generated by terraform (terraform/firebase.tf) from the registered
    // Firebase Web App config — do not edit by hand, run `terraform apply` instead.
    export const environment = {
      firebase: {
        apiKey: '${data.google_firebase_web_app_config.frontend.api_key}',
        authDomain: '${data.google_firebase_web_app_config.frontend.auth_domain}',
        projectId: '${var.project_id}',
      },
      articlesCollection: '${var.firestore_collection}',
      sentimentCollection: '${var.sentiment_collection}',
    };
  EOT
}

resource "google_firebaserules_ruleset" "firestore" {
  project = var.project_id

  source {
    files {
      name    = "firestore.rules"
      content = file("${var.source_dir}/frontend/firestore.rules")
    }
  }

  depends_on = [google_firestore_database.default]
}

resource "google_firebaserules_release" "firestore" {
  name         = "cloud.firestore"
  project      = var.project_id
  ruleset_name = "projects/${var.project_id}/rulesets/${google_firebaserules_ruleset.firestore.name}"
}

resource "google_firebase_hosting_site" "frontend" {
  provider = google-beta
  project  = var.project_id
  site_id  = local.hosting_site_id
  app_id   = google_firebase_web_app.frontend.app_id

  depends_on = [google_firebase_project.default]
}

resource "local_file" "firebaserc" {
  filename = "${var.source_dir}/frontend/.firebaserc"
  content = jsonencode({
    projects = { default = var.project_id }
    targets = {
      (var.project_id) = {
        hosting = { frontend = [local.hosting_site_id] }
      }
    }
  })
}

resource "local_file" "firebase_json" {
  filename = "${var.source_dir}/frontend/firebase.json"
  content = jsonencode({
    hosting = {
      target   = "frontend"
      public   = "dist/frontend/browser"
      ignore   = [".git", "**/node_modules/**"]
      rewrites = [{ source = "**", destination = "/index.html" }]
    }
    firestore = { rules = "firestore.rules" }
  })
}

# Builds the Angular app with the config written above and deploys it to the
# Hosting site. Requires `npm install` to have been run once in frontend/, and
# credentials the Firebase CLI can use non-interactively (either `firebase
# login`, or GOOGLE_APPLICATION_CREDENTIALS pointing at a service account key
# with the Firebase Hosting Admin + Firebase Rules Admin roles).
resource "null_resource" "frontend_deploy" {
  # Rebuilds and redeploys on every `apply` — matches how a backend source
  # change already forces a new Cloud Functions revision in this project (see
  # storage.tf); avoids hashing frontend/src (fileset()/filesha1() give
  # "inconsistent result" errors when evaluated in the same apply as the
  # local_file resources above that write into that same directory).
  triggers = {
    always_run = timestamp()
  }

  provisioner "local-exec" {
    working_dir = "${var.source_dir}/frontend"
    command     = "npm run build && npx --yes firebase-tools deploy --only hosting:frontend --project ${var.project_id} --non-interactive"
  }

  depends_on = [
    local_file.frontend_environment,
    local_file.firebase_json,
    local_file.firebaserc,
    google_firebaserules_release.firestore,
    google_firebase_hosting_site.frontend,
  ]
}
